// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3_71E1DkH_tJAUksjkDan29p-HuBiuP4',
    appId: '1:1048230953763:web:6d1d375c1690cbd2f88296',
    messagingSenderId: '1048230953763',
    projectId: 'madhackjobapp',
    authDomain: 'madhackjobapp.firebaseapp.com',
    storageBucket: 'madhackjobapp.appspot.com',
    measurementId: 'G-R9GZQJM7WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNdAsuTRhVdfnH0SiawpHOpJdvmsiUXG4',
    appId: '1:1048230953763:android:9ed97fefba289858f88296',
    messagingSenderId: '1048230953763',
    projectId: 'madhackjobapp',
    storageBucket: 'madhackjobapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD18NCo82rBESiDWQTMptq51I5oh-g3YeY',
    appId: '1:1048230953763:ios:d77fba1fe8614a33f88296',
    messagingSenderId: '1048230953763',
    projectId: 'madhackjobapp',
    storageBucket: 'madhackjobapp.appspot.com',
    iosBundleId: 'com.example.madhackJobApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD18NCo82rBESiDWQTMptq51I5oh-g3YeY',
    appId: '1:1048230953763:ios:d269ead6f5843e78f88296',
    messagingSenderId: '1048230953763',
    projectId: 'madhackjobapp',
    storageBucket: 'madhackjobapp.appspot.com',
    iosBundleId: 'com.example.madhackJobApp.RunnerTests',
  );
}
